#include "stm32f10x.h"
#include "blocks.h"
#include "multiplex.h"

void EXTI_init(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN; //Timer 4 clock
	// Timer Interrupt
	TIM4->PSC = 0;
	TIM4->ARR = 34464;
	TIM4->CR1 |= TIM_CR1_URS;
	TIM4->DIER |= TIM_DIER_UIE;
	TIM4->EGR |= TIM_EGR_UG;
	NVIC_EnableIRQ(TIM4_IRQn);
	//
	
	//GPIO PA(pins 0,1,2, 3) interrupt
	AFIO->EXTICR[0] |= AFIO_EXTICR1_EXTI0_PA;
	AFIO->EXTICR[1] |= AFIO_EXTICR1_EXTI1_PA;
	AFIO->EXTICR[2] |= AFIO_EXTICR1_EXTI2_PA;
	AFIO->EXTICR[3] |= AFIO_EXTICR1_EXTI3_PA;
	
	EXTI->IMR |= EXTI_IMR_MR0 | EXTI_IMR_MR1 | EXTI_IMR_MR2 | EXTI_IMR_MR3;
	EXTI->FTSR |= EXTI_FTSR_TR0 | EXTI_FTSR_TR1 | EXTI_FTSR_TR2 | EXTI_FTSR_TR3;
	NVIC->ISER[0] |= NVIC_ISER_SETENA_6 | NVIC_ISER_SETENA_7 | NVIC_ISER_SETENA_8 | NVIC_ISER_SETENA_9;
	//
	
}

